# ----------------------------------------------------------------------------
#
# Package             : webdriverio
# Source Repo         : https://github.com/webdriverio/webdriverio
# Travis Job Link     : https://travis-ci.com/github/asellappen/webdriverio/
# Created travis.yml  : No
# Maintainer          : Arumugam N S <asellappen@yahoo.com> / Priya Seth<sethp@us.ibm.com>
#
# Script License      : Apache License, Version 2 or later
#
# ----------------------------------------------------------------------------
language: java

arch:
    - amd64
    - ppc64le

dist: bionic

jdk:
  - openjdk11

install :
 - npm install
 - sudo apt-get install nodejs
 - npm ci
 - node scripts/postinstall
 - node scripts/check-node-version.js
 - husky install
 
script :
 - npm run setup-full
 - npm run test
 - npm run clean && lerna bootstrap --no-ci && npm run link
 - npx run-s test:eslint test:typings test:coverage test:smoke
